#!/bin/bash

#@Author: RB
# Shell Script for Installing JDK, Android Studio & Creating Desktop Icon & more.

BLUE='\033[1;36m'
RED='\033[1;31m'
GREEN='\033[1;32m'
NC='\033[0m'

ZSHRC=$HOME/.zshrc

# This script grabs the latest version for linux from the android studio website. 
STUDIO_URL="$(curl -s https://developer.android.com/studio | grep android/studio/ide-zips | grep linux | awk -F '\"' '{print $2}')"
PLATFORMTOOLS_URL="https://dl.google.com/android/repository/platform-tools-latest-linux.zip"
APKTOOL_URL="https://bitbucket.org$(curl -s https://bitbucket.org/iBotPeaches/apktool/downloads/ | grep apktool_ | head -n 1 | awk -F '\"' '{print $2}')"

# Install JDK24
JDKInstall() {
    echo -e "${GREEN}[*] Installing JDK ${NC}"
    echo -e "${GREEN}[*] Enter your Password then Sit back and Relax ${NC}"
    sudo apt update -y
    sudo apt install openjdk-24-jdk openjdk-24-jre -y
    echo -e "${GREEN}[*] Setting Java Path Variable ${NC}"
    export JAVA_HOME=/usr/lib/jvm/java-24-openjdk-amd64
    echo -e "${GREEN}[*] Testing JAVA_HOME Path ${NC}"
    echo $JAVA_HOME
    echo -e "${GREEN}[*] Adding JAVA bin directory to the PATH variable ${NC}"
    export PATH=$PATH:$JAVA_HOME/bin
    echo -e "${GREEN}[*] Testing PATH Variable ${NC}"
    echo $PATH
    echo -e "${GREEN}[*] Testing Java Installation ${NC}"
    java -version
}

#Changing the opt ownership so we can download and install tools in it such as mobsf, android studio, etc. 
ChangeOptOwnership() {
    echo -e "${GREEN}[*] Changing ownership of /opt to $USER ${NC}"
    sudo chown -R $USER:$USER /opt/
}

# Download Android Studio
DownloadAndroidStudio() {
    echo -e "${GREEN}[*] Downloading Android Studio from $STUDIO_URL ${NC}"
    wget -c "$STUDIO_URL"
}

# Install Fastboot & ADB Tools
FastbootADB() {
    echo -e "${GREEN}[*] Install ADB Tools ${NC}"
    echo -e "${GREEN}[*] Removing the apt version because of some bugs on kali (not detecting adb devices)${NC}"
    sudo apt purge adb android-sdk-platform-tools-common adbd android-sdk-platform-tools-common -y
    echo -e "${GREEN}[*] Downloading and installing platform-tools (adb, fastboot, etc.) from $PLATFORMTOOLS_URL ${NC}"
    wget -c "$PLATFORMTOOLS_URL"
    mkdir ~/Android/Sdk/platform-tools/
    unzip platform-tools-latest-linux.zip -d ~/Android/Sdk/
    rm platform-tools-latest-linux.zip
    echo -e "${GREEN}[*] Done installing ADB Tools ${NC}"
}

# Install Android Studio
InstallAndroidStudio() {
    echo -e "${GREEN}[*] Installing Android Studio ${NC}"
    mkdir -p /opt/android/
    tar -xzf android-studio-*-linux.tar.gz -C /opt/android/
    rm android-studio-*-linux.tar.gz 
    STUDIO_VERSION=$(echo $STUDIO_URL | awk -F '/' '{print $8}')

    echo -e "${GREEN}[*] Creating an Android Studio launcher ($ZSHRC)${NC}"
    mkdir -p "$HOME"/.local/share/applications
    cat >"$HOME"/.local/share/applications/android-studio.desktop <<-EOF
        [Desktop Entry]
        Version=$STUDIO_VERSION
        Type=Application
        Name=Android Studio
        Exec="/opt/android/android-studio/bin/studio" %f
        Icon=/opt/android/android-studio/bin/studio.png
        Categories=Development;IDE;
        Terminal=false
        StartupNotify=true
        StartupWMClass=android-studio
EOF

    chmod +x "$HOME"/.local/share/applications/android-studio.desktop
    cp "$HOME"/.local/share/applications/android-studio.desktop "$HOME"/Desktop/android-studio.desktop

    echo -e "${GREEN}[*] Installing Finished of Android studio${NC}"
    rm -rf android-studio*
    rm -rf StudioInstaller.sh
}

#Setting the environment variables
SetEnvironmentVariables() {
    echo -e "${GREEN}[*] Setting the environment variables ${NC}"

    ANDROID_HOME=$(cat $ZSHRC | grep "ANDROID_HOME")

    echo -e "${GREEN}[*] Setting Android Studio environment variables ($ZSHRC)${NC}"
    if [ -z "$ANDROID_HOME"  ]; then
        echo -e "\n# Android Studio environment variables" >> $ZSHRC
        echo "export ANDROID_SDK_ROOT=$HOME/Android/Sdk" >>  $ZSHRC
        echo "export ANDROID_HOME=$ANDROID_SDK_ROOT" >>  $ZSHRC
        source $HOME/.zshrc

        echo "export PATH=\$PATH:\$HOME/Android/Sdk/tools:\$HOME/Android/Sdk/platform-tools" >>  $ZSHRC
        source $HOME/.zshrc

        if [ ! -z "$ANDROID_HOME"  ]; then
            echo -e "${RED}ANDROID_HOME not set. Android Environment failed ?${NC}"
            exit
        fi
    fi
}

#installing the Mobile Security Framework
InstallMobsf() {
    echo -e "${GREEN}[*] Installing mobsf ${NC}"
    mkdir /opt/android/
    cd /opt/android/
    git clone https://github.com/MobSF/Mobile-Security-Framework-MobSF
    cd Mobile-Security-Framework-MobSF/
    bash ./setup.sh
    cd -
    echo -e "${GREEN}[*] creating an executable in ~/.local/bin/mobsf ${NC}"
    cat >"$HOME"/.local/bin/mobsf <<-EOF
    #!/bin/bash
    #@Author: RB

    #going to attempt to run mobsf from a default location
    cd /opt/android/Mobile-Security-Framework-MobSF/
    bash run.sh & 
    cd -
EOF
}

#reinstall apktool with a better version
ReinstallApktool() {
    echo -e "${GREEN}[*] Reinstalling apktool ${NC}"
    APKTOOL_VERSION=$(echo $APKTOOL_URL | awk -F '/' '{print $7}')
    mkdir -p /opt/android/apktool/
    rm -rf /opt/android/apktool/*
    
    echo -e "${GREEN}[*] Downloading apktool ${NC}"
    sudo curl -L -s $APKTOOL_URL -o /opt/android/apktool/$APKTOOL_VERSION
}



JDKInstall
ChangeOptOwnership
FastbootADB
DownloadAndroidStudio
InstallAndroidStudio
SetEnvironmentVariables
InstallMobsf
ReinstallApktool

echo -e "${GREEN}[*] DONE WITH INSTALLING! ${NC}"
