#!/bin/bash

#A simple script which will generate a keystore for android signing
#@Author: RB
#@version 0.1


BLUE='\033[1;36m'
RED='\033[1;31m'
GREEN='\033[1;32m'
NC='\033[0m'

echo -e "${RED}[*] This script is not for production use since it uses default credentials, which should be modified before making a safe version. ${NC}" 
echo -e "${GREEN}[*] Generating a keystore with keytool for debug purposes. ${NC}" 

keytool -genkey -v -keystore ~/.android/debug.keystore \
  -storepass android -alias androiddebugkey \
  -keypass android -keyalg RSA -keysize 2048 -validity 10000
