#!/bin/bash

#A simple script which will find the frida version from magisk-frida
# WIP
#@Author: RB
#@version 0.1

BLUE='\033[1;36m'
RED='\033[1;31m'
GREEN='\033[1;32m'
NC='\033[0m'

set -e
set -o pipefail

echo -e "${GREEN} This script finds the frida-server version on android through ADB. ${NC}"

adb shell "su -c '/data/local/tmp/frida-server --version'"

