#!/bin/bash

#A simple script which will find the frida version from magisk-frida
# WIP
#@Author: RB
#@version 0.1

BLUE='\033[1;36m'
RED='\033[1;31m'
GREEN='\033[1;32m'
NC='\033[0m'

set -e
set -o pipefail

echo -e "${GREEN} This script finds the frida-server version on android through ADB. ${NC}"
echo -e "${GREEN}[*] The device the app is extracted from is: ${NC}"      
adb devices | sed -n '2p'

echo -e "${GREEN}[*] Using ADB shell to find the frida-server${NC}"  
adb shell "su -c '/data/local/tmp/frida-server --version'"